# Base Iris

Multiclasse Classification

In [ ]:
#Importar dados essenciais
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive/')

dataset = pd.read_csv('/content/drive/My Drive/CursoIA/Multiclass Classification  - base_iris/iris.csv')
dataset

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

# Separando as partes de previsores e classes

In [ ]:
previsores = dataset.iloc[:, 0:4].values
previsores

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
classe = dataset.iloc[:, 4].values
classe

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [ ]:
#Importando lib para split da base
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder #Para transformar classes em números
from tensorflow.keras.utils import to_categorical #Para criar formatar classes com formato 100, 010, 001, de acordo com sua classe


labelEncoder = LabelEncoder()
classe =  labelEncoder.fit_transform(classe)
print(classe)
classe_dummy = to_categorical(classe)
print(classe_dummy)
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe_dummy, test_size=0.25)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.

In [ ]:
#Importando Rede neural
from keras.models import Sequential
from keras.layers import Dense

classificador = Sequential()
classificador.add(Dense(units =  4, # (inputs + outputs)/2
                        activation = 'relu',
                        input_dim = 4))
classificador.add(Dense(units =  4,
                        activation = 'relu'))
classificador.add(Dense(units =  3,
                        activation = 'softmax', # Usada para mais 2 classes de saída
                        input_dim = 4))
classificador.compile(optimizer = 'adam',
                      loss = 'categorical_crossentropy',
                      metrics = ['categorical_accuracy'])

#Treinando rede neural

In [ ]:
classificador.fit(previsores_treinamento,
                  classe_treinamento,
                  batch_size = 10,
                  epochs = 100)

Epoch 1/100
12/12 [==============================] - 2s 3ms/step - loss: 2.2116 - categorical_accuracy: 0.3750
Epoch 2/100
12/12 [==============================] - 0s 2ms/step - loss: 2.0097 - categorical_accuracy: 0.3750
Epoch 3/100
12/12 [==============================] - 0s 2ms/step - loss: 1.8212 - categorical_accuracy: 0.3750
Epoch 4/100
12/12 [==============================] - 0s 4ms/step - loss: 1.6812 - categorical_accuracy: 0.3750
Epoch 5/100
12/12 [==============================] - 0s 6ms/step - loss: 1.5574 - categorical_accuracy: 0.3750
Epoch 6/100
12/12 [==============================] - 0s 4ms/step - loss: 1.4655 - categorical_accuracy: 0.3750
Epoch 7/100
12/12 [==============================] - 0s 4ms/step - loss: 1.3827 - categorical_accuracy: 0.3750
Epoch 8/100
12/12 [==============================] - 0s 3ms/step - loss: 1.3251 - categorical_accuracy: 0.3750
Epoch 9/100
12/12 [==============================] - 0s 4ms/step - loss: 1.2787 - categorical_accuracy: 0.3750
E

In [ ]:
# Verificando resultados
resultados = classificador.evaluate(previsores_teste, classe_teste)
print(resultados)
previsoes = classificador.predict(previsores_teste)
previsoes = (previsoes > 0.5)
classe_teste2 = [np.argmax(t) for t in classe_teste]
previsoes2 = [np.argmax(t) for t in previsoes]
print(previsoes2)
print(classe_teste2)

from sklearn.metrics import confusion_matrix

matrix =  confusion_matrix(previsoes2, classe_teste2)

print(matrix)

2/2 [==============================] - 0s 14ms/step - loss: 1.0809 - categorical_accuracy: 0.4474
[1.0808547735214233, 0.44736841320991516]
2/2 [==============================] - 0s 7ms/step
[0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
[2, 1, 0, 0, 2, 0, 2, 0, 2, 2, 2, 1, 2, 1, 1, 1, 2, 1, 2, 2, 0, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 2, 0, 2, 2, 0, 2]
[[12  8 11]
 [ 0  0  7]
 [ 0  0  0]]
